<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>BrotatoLike</AssemblyName>
    <RootNamespace>BrotatoLike</RootNamespace>
    <SkilmeAIGameOSProject Condition=" '$(SkilmeAIGameOSProject)' == '' ">SkilmeAI/GameOS/SkilmeAI.GameOS.csproj</SkilmeAIGameOSProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SkilmeAIGameOSProject)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="MigrationInput/**/*.cs" />
    <Compile Remove="SkilmeAI/**/*.cs" />
    <Compile Include="SkilmeAI/Src/SceneTests/**/*.cs" />
  </ItemGroup>
</Project>
