-- BrotatoLike DataOS authoring seed.
-- Source: MigrationInput/Data/DataNew, migrated as structured rows for snapshot generation.

PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO data_table(table_id, domain, description) VALUES
    ('unit.player', 'unit', 'BrotatoLike player units'),
    ('unit.enemy', 'unit', 'BrotatoLike enemy units'),
    ('ability', 'ability', 'BrotatoLike abilities');

INSERT OR REPLACE INTO data_record(table_id, record_id, display_name, description) VALUES
    ('unit.player', 'deluyi', '德鲁伊', 'PlayerData.Deluyi'),
    ('unit.enemy', 'yuren', '鱼人', 'EnemyData.Yuren'),
    ('unit.enemy', 'chailangren', '豺狼人', 'EnemyData.Chailangren'),
    ('ability', 'slam', '猛击', 'AbilityData.Slam'),
    ('ability', 'target_point_skill', '位置目标', 'AbilityData.TargetPointSkill'),
    ('ability', 'orbit_skill', '环绕技能', 'AbilityData.OrbitSkill'),
    ('ability', 'sine_wave_shot', '正弦波射击', 'AbilityData.SineWaveShot'),
    ('ability', 'parabola_shot', '定点抛炸弹', 'AbilityData.ParabolaShot'),
    ('ability', 'boomerang_throw', '回旋镖投掷', 'AbilityData.BoomerangThrow'),
    ('ability', 'arc_shot', '圆弧射击', 'AbilityData.ArcShot'),
    ('ability', 'bezier_shot', '贝塞尔射击', 'AbilityData.BezierShot'),
    ('ability', 'dash', '冲刺', 'AbilityData.Dash'),
    ('ability', 'circle_damage', '圆环伤害', 'AbilityData.CircleDamage'),
    ('ability', 'aura_shield', '光环护盾', 'AbilityData.AuraShield');

INSERT OR REPLACE INTO data_field(table_id, record_id, field_key, value_type, value_text) VALUES
    ('unit.player', 'deluyi', 'Collision.Team', 'int', '1'),
    ('unit.player', 'deluyi', 'Damage.MaxHp', 'float', '100'),
    ('unit.player', 'deluyi', 'Damage.CurrentHp', 'float', '100'),
    ('unit.player', 'deluyi', 'Damage.Armor', 'float', '5'),
    ('unit.player', 'deluyi', 'Damage.CritRate', 'float', '5'),
    ('unit.player', 'deluyi', 'Damage.LifeSteal', 'float', '0'),
    ('unit.player', 'deluyi', 'Movement.MoveSpeed', 'float', '200'),
    ('unit.player', 'deluyi', 'Attack.Damage', 'float', '10'),
    ('unit.player', 'deluyi', 'Attack.Range', 'float', '150'),

    ('unit.enemy', 'yuren', 'Collision.Team', 'int', '2'),
    ('unit.enemy', 'yuren', 'Damage.MaxHp', 'float', '150'),
    ('unit.enemy', 'yuren', 'Damage.CurrentHp', 'float', '150'),
    ('unit.enemy', 'yuren', 'Damage.Armor', 'float', '1'),
    ('unit.enemy', 'yuren', 'Movement.MoveSpeed', 'float', '150'),
    ('unit.enemy', 'yuren', 'Attack.Damage', 'float', '6'),
    ('unit.enemy', 'yuren', 'Attack.Range', 'float', '200'),
    ('unit.enemy', 'yuren', 'AI.AttackRange', 'float', '200'),

    ('unit.enemy', 'chailangren', 'Collision.Team', 'int', '2'),
    ('unit.enemy', 'chailangren', 'Damage.MaxHp', 'float', '100'),
    ('unit.enemy', 'chailangren', 'Damage.CurrentHp', 'float', '100'),
    ('unit.enemy', 'chailangren', 'Damage.Armor', 'float', '3'),
    ('unit.enemy', 'chailangren', 'Movement.MoveSpeed', 'float', '150'),
    ('unit.enemy', 'chailangren', 'Attack.Damage', 'float', '5'),
    ('unit.enemy', 'chailangren', 'Attack.Range', 'float', '100'),

    ('ability', 'slam', 'Ability.Name', 'string', '猛击'),
    ('ability', 'slam', 'Ability.Type', 'string', 'Active'),
    ('ability', 'slam', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'slam', 'Ability.TargetSelection', 'string', 'None'),
    ('ability', 'slam', 'Ability.FeatureHandlerId', 'string', '技能.主动.猛击'),
    ('ability', 'slam', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'slam', 'Ability.AutoTargetRange', 'float', '100.300003'),
    ('ability', 'slam', 'Ability.Damage', 'float', '30'),
    ('ability', 'slam', 'Effect.ScenePath', 'string', 'res://assets/Effect/020/AnimatedSprite2D/020.tscn'),

    ('ability', 'target_point_skill', 'Ability.Name', 'string', '位置目标'),
    ('ability', 'target_point_skill', 'Ability.Type', 'string', 'Active'),
    ('ability', 'target_point_skill', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'target_point_skill', 'Ability.TargetSelection', 'string', 'Point'),
    ('ability', 'target_point_skill', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'target_point_skill', 'Ability.AutoTargetRange', 'float', '400'),
    ('ability', 'target_point_skill', 'Ability.Damage', 'float', '10'),

    ('ability', 'orbit_skill', 'Ability.Name', 'string', '环绕技能'),
    ('ability', 'orbit_skill', 'Ability.Type', 'string', 'Passive'),
    ('ability', 'orbit_skill', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'orbit_skill', 'Ability.FeatureHandlerId', 'string', '技能.被动.环绕技能'),
    ('ability', 'orbit_skill', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'orbit_skill', 'Ability.Damage', 'float', '20'),
    ('ability', 'orbit_skill', 'Projectile.ScenePath', 'string', 'res://assets/Projectile/Projectile/Polygon2D/BulletDiamond.tscn'),

    ('ability', 'sine_wave_shot', 'Ability.Name', 'string', '正弦波射击'),
    ('ability', 'sine_wave_shot', 'Ability.Type', 'string', 'Active'),
    ('ability', 'sine_wave_shot', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'sine_wave_shot', 'Ability.FeatureHandlerId', 'string', '技能.投射物.正弦波射击'),
    ('ability', 'sine_wave_shot', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'sine_wave_shot', 'Ability.AutoTargetRange', 'float', '600'),
    ('ability', 'sine_wave_shot', 'Ability.Damage', 'float', '25'),
    ('ability', 'sine_wave_shot', 'Projectile.ScenePath', 'string', 'res://assets/Projectile/Projectile/Polygon2D/ArrowNeedle.tscn'),

    ('ability', 'parabola_shot', 'Ability.Name', 'string', '定点抛炸弹'),
    ('ability', 'parabola_shot', 'Ability.Type', 'string', 'Active'),
    ('ability', 'parabola_shot', 'Ability.TriggerMode', 'string', 'Periodic'),
    ('ability', 'parabola_shot', 'Ability.FeatureHandlerId', 'string', '技能.投射物.定点抛炸弹'),
    ('ability', 'parabola_shot', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'parabola_shot', 'Ability.AutoTargetRange', 'float', '700'),
    ('ability', 'parabola_shot', 'Ability.Damage', 'float', '9'),
    ('ability', 'parabola_shot', 'Effect.ScenePath', 'string', 'res://assets/Effect/004龙卷风/AnimatedSprite2D/004龙卷风.tscn'),
    ('ability', 'parabola_shot', 'Projectile.ScenePath', 'string', 'res://assets/Projectile/Projectile/Polygon2D/ArrowNeedle.tscn'),

    ('ability', 'boomerang_throw', 'Ability.Name', 'string', '回旋镖投掷'),
    ('ability', 'boomerang_throw', 'Ability.Type', 'string', 'Active'),
    ('ability', 'boomerang_throw', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'boomerang_throw', 'Ability.TargetSelection', 'string', 'None'),
    ('ability', 'boomerang_throw', 'Ability.FeatureHandlerId', 'string', '技能.投射物.回旋镖投掷'),
    ('ability', 'boomerang_throw', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'boomerang_throw', 'Ability.AutoTargetRange', 'float', '800'),
    ('ability', 'boomerang_throw', 'Ability.Damage', 'float', '22'),
    ('ability', 'boomerang_throw', 'Projectile.ScenePath', 'string', 'res://assets/Projectile/Projectile/Polygon2D/BulletDiamond.tscn'),

    ('ability', 'arc_shot', 'Ability.Name', 'string', '圆弧射击'),
    ('ability', 'arc_shot', 'Ability.Type', 'string', 'Active'),
    ('ability', 'arc_shot', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'arc_shot', 'Ability.TargetSelection', 'string', 'Entity'),
    ('ability', 'arc_shot', 'Ability.FeatureHandlerId', 'string', '技能.投射物.圆弧射击'),
    ('ability', 'arc_shot', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'arc_shot', 'Ability.AutoTargetRange', 'float', '700'),
    ('ability', 'arc_shot', 'Ability.Damage', 'float', '26'),
    ('ability', 'arc_shot', 'Projectile.ScenePath', 'string', 'res://assets/Projectile/Projectile/Polygon2D/BoomerangChevron.tscn'),

    ('ability', 'bezier_shot', 'Ability.Name', 'string', '贝塞尔射击'),
    ('ability', 'bezier_shot', 'Ability.Type', 'string', 'Active'),
    ('ability', 'bezier_shot', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'bezier_shot', 'Ability.FeatureHandlerId', 'string', '技能.投射物.贝塞尔射击'),
    ('ability', 'bezier_shot', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'bezier_shot', 'Ability.AutoTargetRange', 'float', '600'),
    ('ability', 'bezier_shot', 'Ability.Damage', 'float', '30'),
    ('ability', 'bezier_shot', 'Projectile.ScenePath', 'string', 'res://assets/Projectile/Projectile/Polygon2D/ArrowNeedle.tscn'),

    ('ability', 'dash', 'Ability.Name', 'string', '冲刺'),
    ('ability', 'dash', 'Ability.Type', 'string', 'Active'),
    ('ability', 'dash', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'dash', 'Ability.FeatureHandlerId', 'string', '技能.位移.冲刺'),
    ('ability', 'dash', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'dash', 'Ability.AutoTargetRange', 'float', '300'),
    ('ability', 'dash', 'Effect.ScenePath', 'string', 'res://assets/Effect/lrsc3/AnimatedSprite2D/lrsc3.tscn'),

    ('ability', 'circle_damage', 'Ability.Name', 'string', '圆环伤害'),
    ('ability', 'circle_damage', 'Ability.Type', 'string', 'Passive'),
    ('ability', 'circle_damage', 'Ability.TriggerMode', 'string', 'Permanent'),
    ('ability', 'circle_damage', 'Ability.FeatureHandlerId', 'string', '技能.被动.圆环伤害'),
    ('ability', 'circle_damage', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'circle_damage', 'Ability.AutoTargetRange', 'float', '500'),
    ('ability', 'circle_damage', 'Ability.Damage', 'float', '10'),
    ('ability', 'circle_damage', 'Effect.ScenePath', 'string', 'res://assets/Effect/003/AnimatedSprite2D/003.tscn'),

    ('ability', 'aura_shield', 'Ability.Name', 'string', '光环护盾'),
    ('ability', 'aura_shield', 'Ability.Type', 'string', 'Passive'),
    ('ability', 'aura_shield', 'Ability.TriggerMode', 'string', 'Manual'),
    ('ability', 'aura_shield', 'Ability.FeatureHandlerId', 'string', '技能.被动.光环护盾'),
    ('ability', 'aura_shield', 'Ability.Cooldown', 'float', '1'),
    ('ability', 'aura_shield', 'Ability.Damage', 'float', '15');

INSERT OR REPLACE INTO resource_entry(category, resource_key, resource_path, description) VALUES
    ('Entity', 'PlayerEntity', 'res://Scenes/Main.tscn', 'Temporary player entity scene until migrated scene paths are finalized'),
    ('Asset', 'Unit.Player.Deluyi.Visual', 'res://assets/Unit/Player/deluyi/AnimatedSprite2D/deluyi.tscn', 'PlayerData.Deluyi visual'),
    ('Asset', 'Unit.Enemy.Yuren.Visual', 'res://assets/Unit/Enemy/yuren/AnimatedSprite2D/yuren.tscn', 'EnemyData.Yuren visual'),
    ('Asset', 'Unit.Enemy.Chailangren.Visual', 'res://assets/Unit/Enemy/chailangren/AnimatedSprite2D/chailangren.tscn', 'EnemyData.Chailangren visual'),
    ('Asset', 'Projectile.ArrowNeedle', 'res://assets/Projectile/Projectile/Polygon2D/ArrowNeedle.tscn', 'Projectile visual'),
    ('Asset', 'Projectile.BulletDiamond', 'res://assets/Projectile/Projectile/Polygon2D/BulletDiamond.tscn', 'Projectile visual'),
    ('Asset', 'Projectile.BoomerangChevron', 'res://assets/Projectile/Projectile/Polygon2D/BoomerangChevron.tscn', 'Projectile visual'),
    ('Asset', 'Effect.020', 'res://assets/Effect/020/AnimatedSprite2D/020.tscn', 'Effect visual'),
    ('Asset', 'Effect.004Tornado', 'res://assets/Effect/004龙卷风/AnimatedSprite2D/004龙卷风.tscn', 'Effect visual'),
    ('Asset', 'Effect.lrsc3', 'res://assets/Effect/lrsc3/AnimatedSprite2D/lrsc3.tscn', 'Effect visual'),
    ('Asset', 'Effect.003', 'res://assets/Effect/003/AnimatedSprite2D/003.tscn', 'Effect visual');
